### ISSUE TITLE
파일 업로드시 간헐적으로 일어난 Callback ERROR

### ISSUE THREAD

**Issue by cheese10yun** [INTERTODAY/HC2.0-Project-Admin#6]
`Callback was already called.`

*  대기중인 콜백이 있으면 나타나는 거 같다
*  정확하게 무슨 에러인지 파악 이후 코드 작서할것

ERROR LOG
```
/Users/cheese/intertoday/HC2_Admin/node_modules/async/dist/async.js:837
        if (fn === null) throw new Error("Callback was already called.");
```

-----------

### ERROR LOG
```
null
_http_outgoing.js:367
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:367:11)
    at ServerResponse.header (/Users/cheese/intertoday/HC2_Admin/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/Users/cheese/intertoday/HC2_Admin/node_modules/express/lib/response.js:164:12)
    at ServerResponse.json (/Users/cheese/intertoday/HC2_Admin/node_modules/express/lib/response.js:250:15)
    at Broadcast.uploadCalendar (/Users/cheese/intertoday/HC2_Admin/api/api.js:177:11)
    at Upload.formidable (/Users/cheese/intertoday/HC2_Admin/service/BroadcastService.js:83:5)
    at /Users/cheese/intertoday/HC2_Admin/service/UploadService.js:54:5
    at IncomingForm.<anonymous> (/Users/cheese/intertoday/HC2_Admin/node_modules/formidable/lib/incoming_form.js:105:9)
    at emitNone (events.js:91:20)
    at IncomingForm.emit (events.js:186:7)
```

* callback 문제는 아님
* 최종적으로 API에서 res 객체를 이용해서 반환 시킬때 나타나는 것으로 판단
* 계속 찾아보는중....

### sample code
```javascript
router.post('/upload', (req, res) => {
  form.parse(req, (err, fields, files) => {
    if (!err) {
      console.log('=============================');
      console.log(files);
      console.log('=============================');
      res.end('success');
    }
  });
});
```

### first log
```
{ 'img_files[]\'':
   File {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     size: 33241,
     path: '/Users/cheese/WebstormProjects/s3_img_upload/temp/upload_a4e94f43ef8aa09c947ba4adc5e27012.png',
     name: 'IMG.png',
     type: 'image/png',
     hash: null,
     lastModifiedDate: 2017-02-23T13:40:00.508Z,
     _writeStream:
      WriteStream {
        _writableState: [Object],
        writable: false,
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        path: '/Users/cheese/WebstormProjects/s3_img_upload/temp/upload_a4e94f43ef8aa09c947ba4adc5e27012.png',
        fd: null,
        flags: 'w',
        mode: 438,
        start: undefined,
        autoClose: true,
        pos: undefined,
        bytesWritten: 33241,
        closed: true } } }
```

### second log
```
{ 'img_files[]\'':
   File {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     size: 162672,
     path: '/Users/cheese/WebstormProjects/s3_img_upload/temp/upload_09b29717e30a95ed44dac9ef28aaff3c.png',
     name: 'Visual_SQL_JOINS_V2.png',
     type: 'image/png',
     hash: null,
     lastModifiedDate: 2017-02-23T13:41:37.037Z,
     _writeStream:
      WriteStream {
        _writableState: [Object],
        writable: false,
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        path: '/Users/cheese/WebstormProjects/s3_img_upload/temp/upload_09b29717e30a95ed44dac9ef28aaff3c.png',
        fd: null,
        flags: 'w',
        mode: 438,
        start: undefined,
        autoClose: true,
        pos: undefined,
        bytesWritten: 162672,
        closed: true } } }
{ 'img_files[]\'':
   File {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     size: 162672,
     path: '/Users/cheese/WebstormProjects/s3_img_upload/temp/upload_09b29717e30a95ed44dac9ef28aaff3c.png',
     name: 'Visual_SQL_JOINS_V2.png',
     type: 'image/png',
     hash: null,
     lastModifiedDate: 2017-02-23T13:41:37.037Z,
     _writeStream:
      WriteStream {
        _writableState: [Object],
        writable: false,
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        path: '/Users/cheese/WebstormProjects/s3_img_upload/temp/upload_09b29717e30a95ed44dac9ef28aaff3c.png',
        fd: null,
        flags: 'w',
        mode: 438,
        start: undefined,
        autoClose: true,
        pos: undefined,
        bytesWritten: 162672,
        closed: true } } }
```

* 에러 파악
* 첫 번째 업롣시 정상, 두번째 업로드시 `files`에 2개의 파일이 반복해서 반환
* formidable 에 해당 이슈는 검색 결과 없었습니다.
* 첫번째 업로드 이후 `files`을 반본적으로 돌려주는 현상
* 1번째 업로드시 `files` 정보 1개 2개시 `files` 정보 2개 이렇게 증가
* `async`로 `files` 값을 기반으로 순차적인 작업진행이되어 callback 에러를 출력
* 결과적으로 callback 문제와는 상관 없었습니다.

### before
```javascript
const form = new formidable.IncomingForm();
router.post('/upload', (req, res) => {
  form.parse(req, (err, fields, files) => {
    if (!err) {
      console.log('=============================');
      console.log(files);
      console.log('=============================');
      res.end('success');
    }
  });
});

```

### after

```javascript
router.post('/upload', (req, res) => {
	const form = new formidable.IncomingForm();
  form.parse(req, (err, fields, files) => {
    if (!err) {
      console.log('=============================');
      console.log(files);
      console.log('=============================');
      res.end('success');
    }
  });
});
```

* 로직안에서 form 인스턴스를 생성했더니 문제 해결됬습니다.
* 다른 개발환경에서 동일한 소스코드로 진행 했을 경우 정상작동했습니다.(v7.2.0, 6.7.0)
* 제 환경에서만 동작하지 않았습니다.
* 노드 버전문제일거 같아서 정상작동한 노드버전을 설치해서 테스트한 결과 동일한 문제 발생
* 정확하게 이유는 모르겠습니다.

**Comment by JJ81** [comment]
업로드 에러 현상과 환경에 대해서 자세히 코멘트해주시면 좋을 것 같습니다.
